// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  big: string;
  green: string;
  max: string;
  root: string;
  small: string;
  yellow: string;
}
export const cssExports: CssExports;
export default cssExports;
